//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpSys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public decimal employeeId { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public System.DateTime birthday { get; set; }
        public string emergencyName { get; set; }
        public string emergencyAddress { get; set; }
        public string emergencyContact { get; set; }
        public string employeeStatus { get; set; }
        public decimal sssnum { get; set; }
        public decimal tinnum { get; set; }
        public System.DateTime dateEmployed { get; set; }
        public System.DateTime dateFrom { get; set; }
        public System.DateTime dateTo { get; set; }
        public byte[] signature { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public byte[] image { get; set; }
    }
}
